### ISSUE TITLE
3.0 update syntax highlighting not as good as before

### ISSUE THREAD

**Issue by muchisx** [panoply/vscode-liquid#105]
I think its overwritting the syntax highlighting from the Shopify Liquid Extension, and this extension is not as good as the one from Shopify when it comes to syntax highlighting, so maybe give it less priority (I dont really know how the priority works).

Before it was able to detect what a comment inside a liquid block is and different segmented objects separated by dots ( . )... + a whole lot of stuff.

Now is just a regex mess, can we copy the syntax highlighting from Shopify Liquid or atleast give this extension less priority when having both installed?

**Comment by haroldao** [comment]
Same here....

**Comment by haroldao** [comment]
![image](https://user-images.githubusercontent.com/36776278/193054464-44e6e834-0f9e-41c8-9922-d532d0321736.png)
I downgraded the 2.3.0 and everything is back now 🎉

**Comment by muchisx** [comment]
@haroldao Oh I was wondering where the [schema: ----] snippents went, I thought they were from another extensions, so they also dissapeared with this update? damn. I actually like some of the 3.0 features but I guess we'll have to downgrade for now while this get fixed ?

**Comment by panoply** [comment]
@muchisx
@haroldao 

 It would be huge help if you  guys could shoot me a list of syntax highlights that you prefer or differences you have come across so I can align them. Also note that the grammars in this release are highly customisable and you can extend them to your preferences using the vscode `editor.tokenColorCustomizations` option.
 
 ---
 
If you are keen to try a different theme, you can have a look at [Potion](https://marketplace.visualstudio.com/items?itemName=sissel.material-potion) which I maintain and is highly configured to Liquid.

**Comment by panoply** [comment]
Ah! I see. The `liquid` tag is something I didn't scope, I will get onto this now. Sit tight and keep the updates coming! Thanks so much for the time you are taking to help. I really appreciate it.

**Comment by muchisx** [comment]
@panoply added a couple more stuff, I'll keep editing more through the day ! thank you for your time too 🙏🏼

**Comment by panoply** [comment]
@muchisx Great stuff here! I've got the comments completed and will work through the others. I will have you as co-author on this and reference commits on issue.

**Comment by panoply** [comment]
@muchisx Do you have any other Liquid extensions enabled? The current grammars are not scoped in such a way in some cases. Are you running this extension isolated?

**Comment by muchisx** [comment]
@panoply Finished! I think I covered everything I noticed so far, If I find something else I'll edit and let you know.

I disabled Shopify Liquid for all these comments so nothing else should be interfering, let me test with only Liquid extension enabled, which cases should I compare again?

**Comment by muchisx** [comment]
@panoply I tested again with all extensions disabled and it scoping the same, did I miss something?

**Comment by panoply** [comment]
Ouff. Ignore me, I was testing against the refined grammars 🫠 

---

I will push these fixes tonight plus a couple of additional that improve the syntax support overall. I notice now that a lot of the existing logic implemented was for other Liquid variations, ie: Jekyll/11ty but it seems at second glance I can still support these without sacrificing other variation support.

I am little hesitate on bringing back chained highlights (_Known Shopify objects highlight_) but I will see what I can do. It might need to wait until future releases as the employed logic in Liquify applies this feature semantically. 

> Better [] {} () inside schema

Regarding this logic, it actually as vscode feature `editor.bracketPairColorization` which is disabled by default in **Liquid** which you can enable but it does effect injections applied in external languages, which is why I disabled it. 

---

Overall this was a brilliant issue and has been a huge help for this extension. I will have you as co-author. If you like, maybe join a few of us in the [Liquify Discord](https://discord.gg/eUNEsxMuWt).

**Comment by muchisx** [comment]
@panoply Awesome! Will surely join the discord! Thank you for inviting and taking the time to do this !

As for the _"Known Shopify objects highlight"_ I think you're right, maybe get opinions from other people since its a subjective suggestion, I might like it, others not !

Looking forward to get the update 🙏🏼

**Comment by panoply** [comment]
@muchisx oke, so working through the objects. A lot can be done here. Given the project is using the Liquid Specification created for Liquify means that there is known context for every single object available via the Shopify Liquid variation.

This means that objects which return different outputs can be reflective in the grammers. For example, let's take the `{{ current_page }}` object which only only ever returns a _number_ value.  The grammars could reflect a number scope for this object, eg:

<img width="429" alt="Screenshot 2022-09-29 at 22 25 53" src="https://user-images.githubusercontent.com/7041324/193134819-e5ebd56a-828d-4c4b-b83c-4e232865e350.png">

This can also be applied for different object _types_ take for example `{{ page_title }}` which is a `string` and only ever outputs string types, eg:

<img width="331" alt="Screenshot 2022-09-29 at 22 30 16" src="https://user-images.githubusercontent.com/7041324/193135707-46c4ec8b-0ae7-448f-b34b-8b93cf0a712d.png">

I would vote for this logic to be applied for those objects which only account for a few objects, as most always contain properties, but for those which do not, I think this would be a nice addition as it will inform when it is being called or used what type it is. 

**Note** Whenever a value is re-assigned the highlighting will fallback to punctuation, eg:

<img width="494" alt="Screenshot 2022-09-29 at 22 34 04" src="https://user-images.githubusercontent.com/7041324/193136379-7da497d8-cad8-4538-af62-473cf72480cb.png">

**Comment by muchisx** [comment]
@panoply I like this approach, how would it style objects that return other objects? Like the `products` that returns a shopify productsDrop object if I remember correctly?

**Comment by panoply** [comment]
I'm not sure I've heard of drops, do you mean something like: 

```liquid
{{ object1.object2.object3 }}
```

or ones which return something like an _array_ which can either be iterated or referenced, eg:

```liquid
{{ all_products['some-title'] }}

{% # or alternatively you can iterate %}

{% for product in all_products %}

{% endfor %}
```

**Comment by muchisx** [comment]
@panoply Yes like an array, I guess is just like Shopify calls it, the `products` object contains multiple `product` and Shopify calls it productsDrop or something like that but its definetly an array you can iterate through

you can do like

```
for product in collection.products
...
endfor

```

**Comment by panoply** [comment]
Ah! Yes, this is something I would need to determine to the _best_ scope of grammar to use. Because we are not dealing with a _real_ programming language in Liquid, I don't believe things need to be very strict in this area. Going back to the Liquid Specifications, things could get very creative here. 

Let's take a deeply nested objects, here is this example I am using a mixtures of `variable.language.object.liquid`, `support.type.object.liquid` and `string.other.liquid` as scopes to infer the values. This way when you are referencing an object, you will know when you hit (for example) a `string` type. Depending on what makes most sense.

https://user-images.githubusercontent.com/7041324/193145493-471f2122-c24b-451a-91d2-0819a464187a.mov

This can be done a lot of different ways, here it is reversed.

<img width="524" alt="Screenshot 2022-09-29 at 23 36 36" src="https://user-images.githubusercontent.com/7041324/193146617-89ec1f4f-1cb3-4f8d-988c-7fbcd5f2d62f.png">

You could also implement this on a level basis, so (for example) only apply coloured type scope on the properties on a depth of 1 from the last value, eg: 

<img width="486" alt="Screenshot 2022-09-29 at 23 39 11" src="https://user-images.githubusercontent.com/7041324/193146957-f2699193-32ee-45c8-9486-e7e6e95b046e.png">

Where the `user` value is inferred to a `meta` scope, removing its highlight but the `image` because it contains 1 more value from the end (`src`) the highlight is applied.

**Comment by panoply** [comment]
Actually, let's not get too creative. I think it is best to follow similar logic as was in 2.3 but do things a little more elegant on the ending values and infer their types accordingly. If a Products Drop (array) is referenced either use `variable.language.object.liquid` or `support.type.object.liquid` on expression BUT when another type is referenced, like a _string_, _number_ or _boolean_ then the appropriate scopes for those types are applied. 

This way the syntax colours are cosmic and well inferred but not to a point of unreadability. I suppose there is a fine line there. Essentially, this pattern to follow suite: 

![](https://user-images.githubusercontent.com/7041324/193146957-f2699193-32ee-45c8-9486-e7e6e95b046e.png)

This _feels_ the most logical step forward and will solve the issue while still adding extra flavour.

**Comment by muchisx** [comment]
@panoply Agree! I like both options but true, if there's a big deep nested object it can get very colorful and crazy haha so going with the second option only highlighting the lasts 2 values seems great ! 👏🏼

**Comment by panoply** [comment]
Shipped https://github.com/panoply/vscode-liquid/pull/110

Big thanks to @muchisx
