### ISSUE TITLE
Output'ing Liquid Into Nested Object Breaks Highlighting

### ISSUE THREAD

**Issue by james0r** [panoply/vscode-liquid#15]
This is directly from the theme.liquid file for the Debut theme:

![theme liquid++debut-test+2019-06-13+18-29-29](https://user-images.githubusercontent.com/34731936/59477360-ad9b5980-8e09-11e9-89e3-8e0a9f1db35b.png)

Ext version 1.6.5
VS Code: 1.35.1

**Comment by panoply** [comment]
This issue is unrelated to this extension. 

This extension does not support liquid infused javascript from within `<script>` tags. The errors you are seeing are not coming from this extension but instead your editors linter, eg: eslint. Moustache tags (`{{ }}`) are not valid in the JavaScript language, so logically your linted is going to complain. To avoid this ignore `.liquid` files from being linted by the extension controlling this aspect of your development.

**Comment by james0r** [comment]
Feature Request? The Atom-Liquid package hands the syntax highlighting for the same file just fine.

**Comment by panoply** [comment]
Reopening this as in issue #16 was able to recreate the issue.

**Comment by panoply** [comment]
The main obstacle and different between this extension and the Atom-Liquid extension is the injection highlighting which is part of the issue here. It's also important to note that after some testing on certain color themes will cause highlighting to break, see below using Monokai Soda:


![screencast 2019-06-14 21-44-05](https://user-images.githubusercontent.com/7041324/59534127-b49b9800-8eed-11e9-9436-6fd8634be3db.gif)

**Comment by james0r** [comment]
It's broken for all the color schemes that I have. I just tested it on Monokai Dark Soda (I don't see monokai soda) and it's broken with that as well.

**Comment by panoply** [comment]
Closed in #17

**Comment by james0r** [comment]
Really excited to have that fix! I did find another instance where it's broken though. See here after the single quotes ==> https://monosnap.com/file/yshp5nSrLEz2E82lL1bqByScRn50l4

Here's the code i'm looking at ==> https://gist.github.com/james0r/07bb85bb116bbd35d8d0c2911f4f5f8d

**Comment by panoply** [comment]
You're trying to split a `=` which is really not recommended in any case. I'll have a look but not promising anything.

**Comment by panoply** [comment]
@james0r update to version 1.7.4. I applied a fix.

**Comment by james0r** [comment]
Awesome! looks good.
