### ISSUE TITLE
Formatting issues despite the formatter being disabled

### ISSUE THREAD

**Issue by richayles** [panoply/vscode-liquid#150]
![image](https://user-images.githubusercontent.com/984154/216671334-7a6af6dc-ae17-4e79-98c3-9658dde2446f.png)

Have a schema block laid out as below
![image](https://user-images.githubusercontent.com/984154/216671490-a697345c-a63b-4e5d-bc4a-0bf6c95f6158.png)
I have made a single space addition to the end of the line - and on hitting save it reformats the whole JSON
I've tried a number of different setting change configurations - but it always results in the same auto indent happening
![image](https://user-images.githubusercontent.com/984154/216671643-050ce477-a2ff-4ef5-add8-f4e56b5c35c0.png)

The below seems quite temperamental and clicking on it has no effect at times, and it re-enables itself between changing between files
![image](https://user-images.githubusercontent.com/984154/216671883-7c27b2b3-829f-4691-a05d-4a487a10a2b0.png)

Hoping this is all resolved by v3.4 - is there an expected release date?

**Comment by Arifursdev** [comment]
yes.. it seems this is broken.. despite disabling with 
`{
    "liquid.format.enable": false
}`

it still is the default formatter and formats code on save.

**Comment by panoply** [comment]
Hey guys, 

I apologize for being so late in getting this addressed. I have had a really busy 2023 so far. I am working on this from tomorrow. If you want to turn off formatting, you need to do this using Language Specific VSCode settings, for example:

In your workspace settings:

```jsonc
  "[liquid]": {
    "editor.defaultFormatter": "sissel.shopify-liquid",
    "editor.formatOnSave": false // Make this false
  },
```

This will turn off formatting. 

### Additional Context

The `liquid.format.enable` option will actually be deprecated in the next version (see #132) and moving forward, formatting will be applied using vscode language specific settings (as above). The only reason this option still exists is because of legacy reasons. See #138  PR for more info.

**Comment by panoply** [comment]
@richayles FYI: This is the default behaviour for external code regions in markup. This is why your schema is being indented. It follows common standard when formatting structures. I can look into introducing a rule within Æsthetic to counter that behaviour. 

Let me know.

**Comment by panoply** [comment]
@richayles I'll introduce a new rule to adhere to this behaviour in **v4.0.0** which will be made available to the new `liquid` ruleset. This rule will enable you to override the default behaviour of level indentation being applied to `{% schema %}` code regions. 

This capability will be made available under`dedentTagList` and will accept an array list of Liquid tag names that should not apply indentation. In your case, you'd need to add `schema` to the rule (when it becomes available), eg:

```json
{
   "liquid": {
       "dedentTagList": ["schema"]
   }
}
```

I will inform up its availability in this issue.

**Comment by Arifursdev** [comment]
@panoply sorry, i think it used to have the snippet for both {% %} and {%- -%}
now it just {% %}
