### ISSUE TITLE
Code within Comments Breaks Highlighting

### ISSUE THREAD

**Issue by james0r** [panoply/vscode-liquid#20]
<img width="674" alt="liquid_page-builder-alg liquid++site+2019-07-04+13-09-57" src="https://user-images.githubusercontent.com/34731936/60686391-4c413600-9e5d-11e9-974e-96ee4b44aa13.png">

Not sure whether it's the use of {{ block.type }} or possibly the double forward slashes.

**Comment by panoply** [comment]
Hey @james0r, Thanks for submitting this. I will have the issue resolved in v2.1.4 today sometime. It's because the triple dash  `---` is treated as frontmatter (YAML) which is used in Jekyll. 

I have recently changed the way the extension handles liquid grammars and syntax, so this feedback is very helpful. How are you finding the new version besides this issue?

**Comment by james0r** [comment]
Thank you! Loving it! It's allowed me to stay on VS Code instead of having
to move to Atom.
