### ISSUE TITLE
Do liquid files get treated as HTML syntax? Syntax highlighting/color isn't working, nor is emmet

### ISSUE THREAD

**Issue by adrianocr** [panoply/vscode-liquid#29]
I have the extension installed and it seems to handle all liquid tags, schemas, etc, correctly. But it doesn't seem to treat the rest of the file like a standard HTML file therefore syntax highlighting for html tags isn't working nor is emmet expansions. 

Screenshot: https://cl.ly/42b5a4 and https://cl.ly/6f3899

**Comment by panoply** [comment]
Send your settings.json configuration. Intellisense, Emmet and and Syntax highlighting is working in 3 different environments I have tested as the extension work successfully with 1000's of users.

**Comment by adrianocr** [comment]
@panoply here you go https://pastebin.com/r5UL2bfm

**Comment by adrianocr** [comment]
P.s. I just nuked my entire ~/.config/Code/User/ directory to make sure there weren't any settings or anything conflicting. Reloaded vscode, reopened a liquid file and set the language type to liquid. Still no syntax highlighting: https://cl.ly/e77a3e

**Comment by panoply** [comment]
This is your Global settings, so for starters use a workspace settings. Next, you're defining associations that are redundant, take your following settings:

```json
"files.associations": {
    "*.html": "twig",
    "*.html.liquid": "html",
    "*.liquid": "html"
  },
  "emmet.syntaxProfiles": {
    // "*.scss.liquid": "sass",
    "*.liquid": "html" 
  },
  "emmet.includeLanguages": {
    // "scss.liquid": "sass",
    "*.liquid": "html",
    "twig": "html"
  },
``` 
This is not correct and is probably contributing to your problems. Also, disable your Twig extensions, Liquid and Twig share similar syntax. There is a lot wrong with your configurations. You're association Liquid files to HTML. I mean, honestly, how long have you been working with VS Code? HAve you read the VS Code documentation?

**Comment by panoply** [comment]
> Reloaded vscode, reopened a liquid file and set the language type to liquid.

You don't need to set the language type to Liquid if you're opening a `.liquid` or `.html` file as this extension merely injects Liquid into HTML Grammars. This is not really an issue of the extension this more an issue of incorrect user configurations and quite possibly external extension conflicts.

**Comment by adrianocr** [comment]
@panoply ok I removed my entire `~/.config/Code/` directory. No user settings or files or cache or anything left whatsoever. Also removed my `~/.vscode/extensions/` directory. Re-opened code, isntalled the liquid extension only: https://cl.ly/c66be9. Opened a liquid file which vscode sets as "HTML": https://cl.ly/c66be9. However, this was already working before. I assumed it was broken because there are issues with style blocks. For example: https://cl.ly/6bfe28.

If I set the language to "liquid" manually, the css block errors go away. But then I lose syntax highlighting for standard html: https://cl.ly/6bfe28

Sorry for the multitude of screenshots, I'm a very visual person haha

**Comment by panoply** [comment]
So the syntax highlighting for HTML works, It’s only when you set the language to Liquid that the HTML syntax disappears? 

As mentioned in the readme file under [Syntax Support](https://github.com/panoply/vscode-liquid#syntax-support) you can disable validation of CSS in HTML by setting validations to false.

**Comment by adrianocr** [comment]
@panoply first of all, I corrected the screenshot urls above. I didn't realize I pasted the same screenshot like 3 times. 

Secondly, yes, if the language is set as html (which vscode seems to do automatically for liquid files) then the html syntax highlighting works. But there are issues with script and css blocks as you can see in https://cl.ly/6bfe28. And if I enable formatting it says that it activated but it continues to show a × next to the option. Formatting works though. 

Then if instead I set the language to liquid, not html, all liquid syntax highlighting works (including inside css and script blocks), but html syntax highlighting stops working. 

Honestly, the css and script blocks showing errors is a mild inconvenience. I'll leave it enabled. 

But what I'm wondering is if there is some kind of issue here. Should I be using "HTML" or should I be using "Liquid" as the language mode?

**Comment by panoply** [comment]
Hopefully this will bring some insight to your question:

When you define Liquid as the language you will only receive Liquid syntax, this why when you define your HTML file as Liquid only Liquid code is highlighted.  Liquid does not contain HTML or CSS tags, it only consists of block (`{%  %}`) tags and moustache (`{{ }}`) tags, this means that any tag that is not Liquid, like HTML (`< >`) will not be highlighted. Essentially, when you define HTML files as Liquid you're telling VS Code that all code in that file should be treated as if it were Liquid.  

This extensions works by injecting Liquid syntax (grammar) into HTML, JavaScript, CSS, SCSS and Markdown files, if you read [Syntax Support](https://github.com/panoply/vscode-liquid#syntax-support) section of the readme file you will get a full list of languages that Liquid is injected. 

By default, VS Code validates code contained in `<style>` and `<script>` tags and because Liquid is not valid CSS or JavaScript, VS Code will complain of invalid syntax. You can turn this feature off by applying the following settings to your workspace:

```json
{
  "html.validate.scripts": false,
  "html.validate.styles": false
}
```
This actually documented in the [Syntax Support](https://github.com/panoply/vscode-liquid#syntax-support) section of the readme file. 

The reason you don't see `Liquid` in the Languages status bar item when you open a `.liquid` file is because as before mentioned this extension injects Liquid into HTML because Liquid is generally used in combination with HTML.

**Comment by panoply** [comment]
> Should I be using "HTML" or should I be using "Liquid" as the language mode?

You shouldn't need to define Liquid as a language mode, as it's already active. The only time you would need to define Liquid as a language is in the odd occurrence that you want a file to be treated as Liquid and only Liquid, which is probably going to be never as the extension already supports Liquid in languages that it's commonly found present in (HTML, SCSS etc).

**Comment by adrianocr** [comment]
Ahhhhhh that clarifies everything! I was a bit confused. Ok roger that; everything is working as intended. Thank you so much.
