### ISSUE TITLE
.scss.liquid issue

### ISSUE THREAD

**Issue by megatux** [panoply/vscode-liquid#47]
Sorry if this is an issue with scss support, but if scss.liquid is supported then why there is an error for not valid scss syntax?
![Captura de pantalla de 2020-03-03 11-03-51](https://user-images.githubusercontent.com/850020/75783167-de784180-5d3e-11ea-9f91-add1ba2b7ac4.png)
Should I report it on the scss support page ?

**Comment by panoply** [comment]
Hey @megatux. I only built support for syntax highlighting but not validations which is why you get those errors. You can disable validations on `scss.liquid` files in workspace settings from vscode which will prevent this from occurring.

**Comment by samueltlg** [comment]
Just as a reference for anyone else running into this issue - switching off validation in settings will prevent any errors from popping up, but will not stop the SCSS language-server from giving up searching for subsequent file-symbols, when liquid-syntax is used at the top-level (non-nested) and is encountered by the parser. I have found a workaround to have file-symbols still recognised in the file, and for intellisense to still work. This is particularly useful/essential if you have a very large `.scss.liquid` file, which is I think typicallythe case. To illustrate:

Before:
![image](https://user-images.githubusercontent.com/25965112/97356191-ce920c80-188f-11eb-990d-3e9d32e0a935.png)

(SCSS language-server gives up further parsing any further upon encountering the `{{` liquid object-access initiation characters. In the above example, only one symbol is recognised, when the file actually has thousands).

The issue arises for myself only when using liquid language-structures for top-level variable assignments. However, I noticed that for whatever reason, everything is fine when the first character following the assignment (`$variable:`) is not liquid object access characters or liquid tag-openings (`{%`). So the following workarounds seem to work:

![image](https://user-images.githubusercontent.com/25965112/97356844-c8e8f680-1890-11eb-947d-6d187d53d692.png)
![image](https://user-images.githubusercontent.com/25965112/97356947-ea49e280-1890-11eb-9e76-4d2cc0b9f978.png)
![image](https://user-images.githubusercontent.com/25965112/97356962-f2a21d80-1890-11eb-8684-ab57852cbe61.png)

All that is going on here is the avoidance of using the liquid object/tag opening character-sequences immediately after top-level assignment openings. In these cases, same-type casting is occurring, so that the output from the liquid-construct remains the same in type and contents (e.g. in the first example, the headline_font_size setting is intended to be output as a number). A little trick has been used to keep colors recognised still as colors, by just using a color-modifying function with arguments that do not modify the input. After doing this for all top-level liquid-usage instances, all (top-level at least) symbols are recognised, and intellisense works.

![image](https://user-images.githubusercontent.com/25965112/97357542-db176480-1891-11eb-88f9-98b7f9e710ed.png)

**Comment by panoply** [comment]
🚢  Shipped [v3.0.0](https://github.com/panoply/vscode-liquid/releases/tag/v3.0.0)
