### ISSUE TITLE
Command not found errors

### ISSUE THREAD

**Issue by nova93** [panoply/vscode-liquid#68]
Hey,

Using the current extension, on latest VS Code, none of the commands work, yet they do show up as an option.

After some digging, I've installed the project dependencies in the extension directory

```
~/.vs-code/extensions/sissel.shopify-liquid-2.3.0
```

Restarted the VS Code, and everything now works :-)

**Comment by hrdwdmrbl** [comment]
How does one install the project dependencies? I don't even have that folder...

**Comment by hrdwdmrbl** [comment]
For me the path is `~/.vscode/extensions/sissel.shopify-liquid-2.3.0`

I tried installing dependencies by running `npm install` and restarting, but that didn't solve my problem.

**Comment by hrdwdmrbl** [comment]
I ended up opening the vscode-liquid product in VS Code, and then it asked me for permission to allow some locally installed extensions of this project. After allowing it everywhere, I restarted VS Code yet again and finally it works. 

Unfortunately at the end of the day I found a that the simple VS Code HTML formatter to do a better job. :S

**Comment by hrdwdmrbl** [comment]
I believe all of those were there. What VS Code was complaining about was something like `liquid.formatDocument` commend not found

**Comment by panoply** [comment]
Remove the extension. Restart vscode, reinstall the extension then restart vscode.

**Comment by hrdwdmrbl** [comment]
Yup, tried that already :)

**Comment by Decoherence** [comment]
I kept running into this error as well. Manually adding a `.liquidrc` to the project's root directory made no difference, even after restarts. 

Here's what worked for me.

When I tried saving/creating the workspace (_File > Save Workplace As_), instead of simply adding folders to a workspace, I could suddenly see errors from the `.liquidrc` file I'd created. Progress!

![image](https://user-images.githubusercontent.com/3780824/150612982-f683f80f-e970-4c2f-842f-e8550b22da21.png)

I removed the `.liquidrc` file I'd created, and ran the _Liquid: Generate a .liquidrc rule file_ command. That worked.

_Before:_
<img src="https://user-images.githubusercontent.com/3780824/150613688-40424eea-4d13-426e-b5f3-d9c69c3838fd.png" height="300">

After running _Liquid: Format document:_
<img src="https://user-images.githubusercontent.com/3780824/150613709-73347be9-1cf3-47fa-821f-76dad40dc18a.png" height="300">

It still seems a little flaky, however. I noticed that when opening a file in a new window (but still part of the same workspace), the error returns.

**Comment by JonathanAlumbaugh** [comment]
For future visitors, I solved this issue by simply opening the folder I was working in. I had been trying to format a one-off file, and the extension does not seem to like that. Opening the folder solved everything. 

Thanks for the extension panoply!

![image](https://user-images.githubusercontent.com/9826603/189895319-d8037ab0-5cad-479b-a318-9d0948256bd9.png)

**Comment by panoply** [comment]
Thanks for update @JonathanAlumbaugh 

I am actually planning to ship a well needed update for this extension in the next few days which includes the new [Prettify](https://github.com/panoply/prettify) beautification tool and it should solve the issues that had persisted in the past.

**Comment by panoply** [comment]
🚢  Shipped in [v3.0.0](https://github.com/panoply/vscode-liquid/releases/tag/v3.0.0)

These issues should no longer persist. Open up a new issue if you have any trouble. Take a look at the new [readme](https://github.com/panoply/vscode-liquid).
