### ISSUE TITLE
Please publish in Open-VSX for VSCodium users

### ISSUE THREAD

**Issue by sriharshachilakapati** [panoply/vscode-liquid#72]
VSCodium, the telemetry-less fork of VSCode uses Open-VSX instead of Microsoft Marketplace due to licensing restrictions. I request you to publish this extension in Open-VSX too so that we can use it.

**Comment by panoply** [comment]
Will do!

**Comment by akosyakov** [comment]
We are running Web version of Code in Gitpod: www.gitpod.io

his version is not allowed to use MS VS Code extensions Marketplace, since it is not MS product. So we connect to Open VSX instead: https://open-vsx.org/ It is a vendor neutral alternative.

Our users want to install this extension but fail since it is not published to Open VSX: https://community.gitpod.io/t/support-for-liquid-highlight-syntax/4417

Please publish it as well there 🙏 Docs are here: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions Technically it should be straightforward. You are basically have to get a token and call ovsx publish with it, for instance how RedHat is publishing the java extension: https://github.com/redhat-developer/vscode-java/blob/ff51dbffc30dd23190335c929e9f34ccdf511554/Jenkinsfile#L73-L82

**Comment by panoply** [comment]
I've tried doing this several times now and just keep getting internal server errors, anyone can assist?

**Comment by panoply** [comment]
Hej Fam, We good on this.  I'm awaiting namespace verification. Moving this to #91 until verification completes.
